--DROP TABLE MEMBERS;
CREATE TABLE MEMBERS (
    IDX NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(30),
    AGE NUMBER(3),
    ADDR VARCHAR2(150),
    REGDATE DATE DEFAULT SYSDATE
);
--DROP SEQUENCE MEMBERS_SEQ;
CREATE SEQUENCE MEMBERS_SEQ NOCACHE; --시퀀스 생성

INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동1', 27, '서울', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '홍길동2', 30, '대전', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '김유신', 40, '대구', SYSDATE);
INSERT INTO MEMBERS
VALUES (MEMBERS_SEQ.NEXTVAL, '이순신', 38, '부산', SYSDATE);
COMMIT;

SELECT * FROM MEMBERS;